services:

  localstack:
    container_name: "recipients-localstack-4.6.0"
    image: localstack/localstack:4.6.0
    ports:
      - '127.0.0.1:4572:4566'
    environment:
      SERVICES: dynamodb, kinesis
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
      LS_LOG: ${LS_LOG:-debug}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/_localstack/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - recipients-network
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ./localstack:/etc/localstack/init/ready.d
      - recipients-localstack-volume:/var/lib/localstack

  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: recipients-prometheus
    volumes:
      - recipients-prometheus-volume:/prometheus
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - recipients-network

  recipients-service:
    container_name: recipients-service
    image: jcondotta/recipients-service:1.0.0
    depends_on:
      localstack:
        condition: service_healthy
    ports:
      - "8096:8080"
    networks:
      - recipients-network
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: local

      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test

      AWS_DYNAMODB_RECIPIENTS_TABLE_NAME: recipients
      AWS_KINESIS_RECIPIENTS_CREATED_STREAM_NAME: recipients.created
      AWS_KINESIS_RECIPIENTS_DELETED_STREAM_NAME: recipients.deleted

      BANK_ACCOUNTS_API_BASE_URL: http://host.docker.internal:8090

      AWS_DYNAMODB_ENDPOINT: http://localstack:4566
      AWS_KINESIS_ENDPOINT: http://localstack:4566

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  recipients-localstack-volume:
    name: recipients-localstack-data
  recipients-prometheus-volume:
    name: recipients-prometheus-data

networks:
  recipients-network:
    name: recipients-network