services:

  localstack:
    container_name: "recipients-localstack-4.6.0"
    image: localstack/localstack:4.6.0
    ports:
      - '127.0.0.1:4572:4566'
    environment:
      SERVICES: dynamodb, kinesis
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
      LS_LOG: ${LS_LOG:-debug}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/_localstack/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - recipients-network
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ./localstack:/etc/localstack/init/ready.d
      - recipients-localstack-volume:/var/lib/localstack

  redis:
    image: redis:7.4.3
    container_name: recipients-redis-7.4.3
    restart: on-failure
    ports:
      - "6382:6379"
    volumes:
      - recipients-redis-volume:/data
    networks:
      - recipients-network
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping || exit 1" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: recipients-prometheus
    volumes:
      - recipients-prometheus-volume:/prometheus
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - recipients-network

volumes:
  recipients-localstack-volume:
    name: recipients-localstack-data
  recipients-redis-volume:
    name: recipients-redis-data
  recipients-prometheus-volume:
    name: recipients-prometheus-data

networks:
  recipients-network:
    name: recipients-network