server:
  port: 8096

spring:
  application:
    name: account-recipients

  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

cloud:
  aws:
    region:
      static: ${AWS_DEFAULT_REGION}
    dynamodb:
      tables:
        account-recipients:
          table-name: ${AWS_DYNAMODB_ACCOUNT_RECIPIENTS_TABLE_NAME}

api:
  v1:
    account-recipients:
      root-path: '/api/v1/bank-accounts/{bank-account-id}/account-recipients'
      account-recipient-id-path: '/api/v1/bank-accounts/{bank-account-id}/account-recipients/{account-recipient-id}'

client:
  api:
    bank-accounts:
      base-url: 'http://localhost:8090'

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics
  metrics:
    tags:
      application: ${spring.application.name}
#      environment: ${ENVIRONMENT:local}
    distribution:
      percentiles-histogram:
        http.server.requests: true
        account.recipients.create: true
        account.recipients.query: true
        cache.get: true
        cache.put_if_absent: true
        cache.put: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
        account.recipients.create: 0.5, 0.95, 0.99
        account.recipients.query: 0.5, 0.95, 0.99
        cache.get: 0.5, 0.95, 0.99
        cache.put_if_absent: 0.5, 0.95, 0.99
        cache.put: 0.5, 0.95, 0.99


