spring:
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6382

cloud:
  aws:
    region:
      static: us-east-1
    credentials:
      access-key-id: test
      secret-key: test
    dynamodb:
      endpoint: http://localhost:4572
      tables:
        account-recipients:
          table-name: 'account-recipients'